spring.application.name=apex

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

jwt.issuer=${JWT_ISSUER:Apex}
jwt.audience=${JWT_AUDIENCE:Apex.Clients}
jwt.expiration-minutes=${JWT_EXPIRATION_MINUTES:15}
jwt.signing-key=${JWT_SIGNING_KEY}

management.endpoints.web.exposure.include=health
management.endpoints.web.base-path=/
management.endpoints.web.path-mapping.health=health
